name: 'pr-publishing'
description: 'Upload PR contents'

inputs:
  root-dir:
    description: 'The root directory of the Gradle project'
    default: '.'
  publishing-task:
    description: 'The task to run to publish'
    default: 'publishAllPublicationsTo_githubPackages_PRsRepository'

runs:
  using: 'composite'
  steps:
    - name: Compute init script path
      id: initscriptpath
      shell: bash
      run: |
        echo "path=$(echo $GITHUB_ACTION_PATH)/init.gradle" >> $GITHUB_OUTPUT
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
    - name: Publish with Gradle to directory
      run: ./gradlew ${{ inputs.publishing-task }} --init-script ${{ steps.initscriptpath.outputs.path }}
      shell: bash
    - uses: actions/upload-artifact@v4
      name: Upload maven directory
      with:
        name: maven-publish
        path: ${{ inputs.root-dir }}/_packages_prs
